# Generated by Django 5.2.1 on 2025-05-08 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlist', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='score',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
